# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Windows_WorkFolder\工作文件夹\PyQt4toQt5_example\ch_9_layout\paymentdlg.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_paymentDlg(object):
    def setupUi(self, paymentDlg):
        paymentDlg.setObjectName("paymentDlg")
        paymentDlg.resize(458, 615)
        self.verticalLayout = QtWidgets.QVBoxLayout(paymentDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(paymentDlg)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.formLayout_7 = QtWidgets.QFormLayout(self.page)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_4.addWidget(self.lineEdit_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.page)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.comboBox_3 = QtWidgets.QComboBox(self.page)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.formLayout_7.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_3)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.formLayout_6 = QtWidgets.QFormLayout(self.page_3)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_5.addWidget(self.lineEdit_9, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_5.addWidget(self.lineEdit_10, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_5.addWidget(self.lineEdit_11, 2, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.page_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 3, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_5.addWidget(self.lineEdit_12, 3, 1, 1, 1)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_5)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.formLayout_8 = QtWidgets.QFormLayout(self.page_2)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_6.addWidget(self.lineEdit_18, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.page_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 0, 0, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_6.addWidget(self.lineEdit_19, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.page_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.page_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 1, 0, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_6.addWidget(self.lineEdit_20, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.page_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 3, 0, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_6.addWidget(self.lineEdit_21, 3, 1, 1, 1)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_6)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.page_4)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_7 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout_7.addWidget(self.radioButton_7, 0, 4, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout_7.addWidget(self.radioButton_8, 0, 1, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_7.addWidget(self.radioButton_9, 0, 2, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_7.addWidget(self.radioButton_10, 0, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.page_4)
        self.label_29.setObjectName("label_29")
        self.gridLayout_7.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.page_4)
        self.label_30.setObjectName("label_30")
        self.gridLayout_7.addWidget(self.label_30, 1, 0, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_7.addWidget(self.lineEdit_22, 1, 1, 1, 4)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_7)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 8, 0, 1, 8)
        self.comboBox_4 = QtWidgets.QComboBox(paymentDlg)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 3, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(paymentDlg)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(paymentDlg)
        self.groupBox.setMinimumSize(QtCore.QSize(180, 50))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 138, 20))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_3.addWidget(self.radioButton_6)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(paymentDlg)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(paymentDlg)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(paymentDlg)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(paymentDlg)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(paymentDlg)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(paymentDlg)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(paymentDlg)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(paymentDlg)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(paymentDlg)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout = QtWidgets.QFormLayout(self.tab)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 3, 1, 1, 1)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_3.addWidget(self.lineEdit_13, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_3.addWidget(self.lineEdit_14, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_3.addWidget(self.lineEdit_15, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_3.addWidget(self.lineEdit_16, 3, 1, 1, 1)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.formLayout_4 = QtWidgets.QFormLayout(self.tab_6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_4.addWidget(self.radioButton_4, 0, 4, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_4.addWidget(self.radioButton, 0, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_4.addWidget(self.radioButton_2, 0, 2, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_4.addWidget(self.radioButton_3, 0, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 1, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_4.addWidget(self.lineEdit_17, 1, 1, 1, 4)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_4)
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout.addWidget(self.tabWidget, 7, 0, 1, 8)
        self.buttonBox = QtWidgets.QDialogButtonBox(paymentDlg)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 10, 3, 1, 5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 5, 1, 1)
        self.moreButton = QtWidgets.QPushButton(paymentDlg)
        self.moreButton.setObjectName("moreButton")
        self.gridLayout.addWidget(self.moreButton, 10, 0, 1, 1)
        self.goodsGroup = QtWidgets.QGroupBox(paymentDlg)
        self.goodsGroup.setObjectName("goodsGroup")
        self.formLayout_9 = QtWidgets.QFormLayout(self.goodsGroup)
        self.formLayout_9.setObjectName("formLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox_2 = QtWidgets.QCheckBox(self.goodsGroup)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_8.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.goodsGroup)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_8.addWidget(self.checkBox_3, 0, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.goodsGroup)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_8.addWidget(self.checkBox_4, 3, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.goodsGroup)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_8.addWidget(self.checkBox, 2, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.goodsGroup)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_8.addWidget(self.checkBox_5, 0, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.goodsGroup)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_8.addWidget(self.checkBox_6, 1, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.goodsGroup)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_8.addWidget(self.checkBox_8, 2, 1, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.goodsGroup)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_8.addWidget(self.checkBox_7, 3, 1, 1, 1)
        self.formLayout_9.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.gridLayout_8)
        self.gridLayout.addWidget(self.goodsGroup, 5, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 6, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(paymentDlg)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(paymentDlg)

    def retranslateUi(self, paymentDlg):
        _translate = QtCore.QCoreApplication.translate
        paymentDlg.setWindowTitle(_translate("paymentDlg", "Dialog"))
        self.label_13.setText(_translate("paymentDlg", "收银员编号"))
        self.label_14.setText(_translate("paymentDlg", "货币种类"))
        self.comboBox_3.setItemText(0, _translate("paymentDlg", "人民币"))
        self.comboBox_3.setItemText(1, _translate("paymentDlg", "美元"))
        self.comboBox_3.setItemText(2, _translate("paymentDlg", "日元"))
        self.comboBox_3.setItemText(3, _translate("paymentDlg", "港币"))
        self.comboBox_3.setItemText(4, _translate("paymentDlg", "新台币"))
        self.comboBox_3.setItemText(5, _translate("paymentDlg", "其他"))
        self.label_15.setText(_translate("paymentDlg", "支付宝账户"))
        self.label_16.setText(_translate("paymentDlg", "折扣"))
        self.label_23.setText(_translate("paymentDlg", "客服付款"))
        self.label_24.setText(_translate("paymentDlg", "实收款"))
        self.label_25.setText(_translate("paymentDlg", "微信账户"))
        self.label_26.setText(_translate("paymentDlg", "折扣"))
        self.label_27.setText(_translate("paymentDlg", "客服付款"))
        self.label_28.setText(_translate("paymentDlg", "实收款"))
        self.radioButton_7.setText(_translate("paymentDlg", "其他"))
        self.radioButton_8.setText(_translate("paymentDlg", "银联"))
        self.radioButton_9.setText(_translate("paymentDlg", "VISA"))
        self.radioButton_10.setText(_translate("paymentDlg", "MasterCard"))
        self.label_29.setText(_translate("paymentDlg", "类型"))
        self.label_30.setText(_translate("paymentDlg", "卡号"))
        self.comboBox_4.setItemText(0, _translate("paymentDlg", "现金"))
        self.comboBox_4.setItemText(1, _translate("paymentDlg", "支付宝"))
        self.comboBox_4.setItemText(2, _translate("paymentDlg", "微信支付"))
        self.comboBox_4.setItemText(3, _translate("paymentDlg", "银联/VISA/MasterCard"))
        self.groupBox.setTitle(_translate("paymentDlg", "支付选项"))
        self.radioButton_5.setText(_translate("paymentDlg", "多种(默认)"))
        self.radioButton_6.setText(_translate("paymentDlg", "一种"))
        self.label.setText(_translate("paymentDlg", "姓名"))
        self.comboBox.setItemText(0, _translate("paymentDlg", "一般零售客户"))
        self.comboBox.setItemText(1, _translate("paymentDlg", "重点大客户"))
        self.comboBox.setItemText(2, _translate("paymentDlg", "大客户"))
        self.comboBox.setItemText(3, _translate("paymentDlg", "重点零售客户"))
        self.label_3.setText(_translate("paymentDlg", "识别码"))
        self.label_4.setText(_translate("paymentDlg", "消费金额"))
        self.label_2.setText(_translate("paymentDlg", "类型"))
        self.label_12.setText(_translate("paymentDlg", "支付方式"))
        self.label_5.setText(_translate("paymentDlg", "收银员编号"))
        self.label_6.setText(_translate("paymentDlg", "货币种类"))
        self.comboBox_2.setItemText(0, _translate("paymentDlg", "人民币"))
        self.comboBox_2.setItemText(1, _translate("paymentDlg", "美元"))
        self.comboBox_2.setItemText(2, _translate("paymentDlg", "日元"))
        self.comboBox_2.setItemText(3, _translate("paymentDlg", "港币"))
        self.comboBox_2.setItemText(4, _translate("paymentDlg", "新台币"))
        self.comboBox_2.setItemText(5, _translate("paymentDlg", "其他"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("paymentDlg", "现金"))
        self.label_7.setText(_translate("paymentDlg", "支付宝账户"))
        self.label_10.setText(_translate("paymentDlg", "折扣"))
        self.label_8.setText(_translate("paymentDlg", "客服付款"))
        self.label_9.setText(_translate("paymentDlg", "实收款"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("paymentDlg", "支付宝"))
        self.label_17.setText(_translate("paymentDlg", "微信账户"))
        self.label_18.setText(_translate("paymentDlg", "折扣"))
        self.label_19.setText(_translate("paymentDlg", "客服付款"))
        self.label_20.setText(_translate("paymentDlg", "实收款"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("paymentDlg", "微信支付"))
        self.radioButton_4.setText(_translate("paymentDlg", "其他"))
        self.radioButton.setText(_translate("paymentDlg", "银联"))
        self.radioButton_2.setText(_translate("paymentDlg", "VISA"))
        self.radioButton_3.setText(_translate("paymentDlg", "MasterCard"))
        self.label_22.setText(_translate("paymentDlg", "类型"))
        self.label_21.setText(_translate("paymentDlg", "卡号"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("paymentDlg", "银联/VISA/MC"))
        self.moreButton.setText(_translate("paymentDlg", "&More"))
        self.goodsGroup.setTitle(_translate("paymentDlg", "购置类型"))
        self.checkBox_2.setText(_translate("paymentDlg", "宝马"))
        self.checkBox_3.setText(_translate("paymentDlg", "奔驰"))
        self.checkBox_4.setText(_translate("paymentDlg", "凯迪拉克"))
        self.checkBox.setText(_translate("paymentDlg", "皇冠"))
        self.checkBox_5.setText(_translate("paymentDlg", "劳斯莱斯"))
        self.checkBox_6.setText(_translate("paymentDlg", "特斯拉"))
        self.checkBox_8.setText(_translate("paymentDlg", "戴森"))
        self.checkBox_7.setText(_translate("paymentDlg", "苹果"))

